const copy = {
  en: {
    'nav.features':'Features','nav.advanced':'Advanced','nav.faq':'FAQ',
    'hero.eyebrow':'A calmer browser, one tab at a time','hero.title':'Name every<br><em>important</em> tab.','hero.copy':'A focused Chrome extension for giving crowded tabs a name that makes sense to you. Local-first. No account. No tracking.','hero.cta':'Add to Chrome','hero.secondary':'See how it works','hero.microcopy':'Free · no ads · data stays in your browser','stage.label':'your browser, made legible',
    'statement.eyebrow':'Why Tab Rename','statement.title':'A useful name is<br>a tiny act of <em>clarity.</em>','statement.copy':'Projects sprawl. Dashboards all look alike. Tabs multiply. Tab Rename lets you replace browser noise with the words you already use to think.',
    'vertical.eyebrow':'Made for vertical tab bars','vertical.title':'When every tab starts<br>the same, context gets <em>lost.</em>','vertical.copy':'Issue trackers, pull-request queues, docs and dashboards often repeat the same title prefix. In a narrow vertical tab bar, the meaningful part is cut off — leaving several open tabs that look identical.','vertical.note':'Illustrative workflow · fictitious domains, representative browser state','vertical.comparisonLabel':'Before and after comparison of repeated vertical browser tabs','vertical.before.label':'Before','vertical.before.copy':'Repeated prefixes hide the difference.','vertical.after.label':'After','vertical.after.copy':'Rules put the useful signal first.','vertical.rule.eyebrow':'One reusable rule','vertical.rule.copy':'Match the changing part of a familiar URL and bring it to the start of the title. The original page title stays there; the distinction arrives first.','vertical.rule.label':'Example URL pattern to title rule','vertical.rule.url':'URL pattern','vertical.rule.title':'Title rule','vertical.link':'Build a rule for your workspace',
    'how.eyebrow':'Three ways to keep a name','how.title':'As temporary — or as lasting — as you need.','scope.page.title':'This page','scope.page.copy':'Name a page for the moment. Navigate away and it disappears.','scope.session.title':'This tab session','scope.session.copy':'Keep the name across reloads and in-page navigation, until you close the tab.','scope.rule.title':'A permanent rule','scope.rule.copy':'Save a local rule and let Tab Rename apply it every time the right page opens.',
    'features.eyebrow':'Built for the long list','features.title':'Small controls. Serious order.','feature.keyboard.title':'Keyboard-first','feature.keyboard.copy':'Open it with a shortcut. Enter saves. Escape closes. Nothing gets between you and the tab.','feature.menu.title':'Right where you work','feature.menu.copy':'Use the toolbar icon or the page context menu when a name needs changing.','feature.local.title':'Private by default','feature.local.copy':'No network requests, telemetry or uploads. Rules and settings stay in Chrome storage on your device.','feature.rules.title':'Rules you can inspect','feature.rules.copy':'Search, edit, pause, export and import every permanent naming rule in one place.','features.caption':'Every saved rule is visible, editable and entirely local.',
    'advanced.eyebrow':'For repeatable work','advanced.title':'Rules that understand<br>where you <em>are.</em>','advanced.copy':'Match one exact URL, a whole domain, or dynamic paths using placeholders and regular expressions. Give recurring work its own visual language.','advanced.link':'Explore advanced rules','advanced.example':'Capture the part that matters, keep it in the title.',
    'faq.title':'A few good questions.','faq.one.q':'Does Tab Rename collect my data?','faq.one.a':'No. Page titles, URLs, rules and settings are processed and stored only in your browser. Tab Rename makes no network requests and has no telemetry.','faq.two.q':'Which pages can I rename?','faq.two.a':'Most normal web pages work. Chrome-protected pages such as chrome://, the Chrome Web Store, new-tab pages and other extension pages cannot be modified.','faq.three.q':'How are overlapping rules resolved?','faq.three.a':'The priority is exact URL, then URL pattern, then domain. A page-only or tab-session name always takes priority over a saved rule.','faq.four.q':'Why does it ask for optional site access?','faq.four.a':'Optional site access lets a permanent rule apply automatically after you navigate. You can deny or revoke it at any time; manual renaming still works.',
    'final.eyebrow':'Make room to think','final.title':'Your tabs already say enough.<br><em>Make them say the right thing.</em>','final.cta':'Add Tab Rename to Chrome','footer.note':'A quieter way to browse.','footer.privacy':'Privacy','back':'← Back to overview',
    'advancedpage.eyebrow':'Advanced rules','advancedpage.title':'Let repeat work<br>name <em>itself.</em>','advancedpage.copy':'A rule can be as precise as one URL or as broad as an entire domain. Everything stays local, visible and under your control.','type.exact.title':'Exact URL','type.exact.copy':'Give one fixed page a dependable name. Perfect for a dashboard, a document or the one link you return to all day.','type.pattern.title':'URL pattern','type.pattern.copy':'Use {1} placeholders or regular-expression capture groups for URLs that change while their meaning stays the same.','type.domain.title':'Domain','type.domain.copy':'Apply a clear, shared name to every page under one hostname. Ideal for admin tools and environments.','priority.eyebrow':'Predictable by design','priority.title':'One page. One clear winner.','priority.copy':'When multiple rules match, Tab Rename resolves them in a fixed order. A name created directly on the page always wins.','priority.one':'Page or tab-session name','priority.two':'Exact URL','priority.three':'URL pattern','priority.four':'Domain','advancedpage.screeneyebrow':'All your rules, in one place','advancedpage.screentitle':'Designed to be changed.','advancedpage.final':'A better title is only<br><em>one shortcut away.</em>',
    'privacy.eyebrow':'Plain-language privacy','privacy.title':'Nothing leaves<br><em>your browser.</em>','privacy.lead':'Tab Rename was built to organize tabs — not to observe the people using them.','privacy.one.title':'What we collect','privacy.one.copy':'Nothing. Tab Rename does not collect, transmit, sell or share personal information. It makes no network requests, contains no analytics and has no advertising SDKs.','privacy.two.title':'What stays on your device','privacy.two.copy':'Permanent rules and paused sites live in Chrome local storage. Names held for a tab session live in Chrome session storage. A page-only name lives only in the current page’s extension memory.','privacy.three.title':'Why optional site access exists','privacy.three.copy':'If you choose to enable it, optional access lets permanent rules apply after a page navigates. It is used only to read and update the current tab title on sites you authorize. You can remove this access in Chrome at any time.','privacy.four.title':'Your controls','privacy.four.copy':'You can edit, disable, export or delete rules from the extension’s management page. Uninstalling the extension removes its local browser data.','privacy.contact':'For the full source and issue tracking, visit the project on GitHub.'
  },
  zh: {
    'nav.features':'功能','nav.advanced':'高级功能','nav.faq':'常见问题','hero.eyebrow':'让浏览器清爽一点，从一个标签开始','hero.title':'给每一个<br><em>重要</em>标签命名。','hero.copy':'一款专注的 Chrome 扩展，让拥挤的标签拥有真正有意义的名字。本地优先，无需账号，不做追踪。','hero.cta':'添加至 Chrome','hero.secondary':'了解工作方式','hero.microcopy':'免费 · 无广告 · 数据只留在浏览器中','stage.label':'让你的浏览器一目了然',
    'statement.eyebrow':'为什么是 Tab Rename','statement.title':'一个好名字，<br>就是一点 <em>清晰。</em>','statement.copy':'项目不断延展，仪表盘看起来千篇一律，标签越开越多。Tab Rename 让你用自己熟悉的词汇，替换浏览器里的噪音。','vertical.eyebrow':'为垂直标签栏而设计','vertical.title':'当每个标签都以<br>同样的文字开头，重点就 <em>丢了。</em>','vertical.copy':'项目管理、代码评审、文档和仪表盘常有相同的标题前缀。在窄窄的垂直标签栏里，真正重要的部分被截断，多个打开的标签看起来一模一样。','vertical.note':'示意工作流 · 虚构域名，模拟常见浏览器状态','vertical.comparisonLabel':'重命名前后：垂直浏览器标签的对比','vertical.before.label':'重命名前','vertical.before.copy':'重复前缀遮住了真正的差异。','vertical.after.label':'重命名后','vertical.after.copy':'规则把有用的信息放到最前面。','vertical.rule.eyebrow':'一条可复用规则','vertical.rule.copy':'匹配熟悉网址中变化的部分，再把它放在标题开头。原页面标题仍会保留，只是关键差异会先出现。','vertical.rule.label':'网址模式到标题规则的示例','vertical.rule.url':'网址模式','vertical.rule.title':'标题规则','vertical.link':'为你的工作区建立规则','how.eyebrow':'三种保存范围','how.title':'可以临时，也可以一直保留。','scope.page.title':'仅当前页面','scope.page.copy':'为这一刻命名。离开页面后，名称自动消失。','scope.session.title':'当前标签会话','scope.session.copy':'刷新或页内跳转后仍会保留，关闭标签才会清除。','scope.rule.title':'永久规则','scope.rule.copy':'把规则保存到本地，每次打开匹配页面时自动应用。',
    'features.eyebrow':'为长长的标签列表而生','features.title':'小小控制，井然有序。','feature.keyboard.title':'键盘优先','feature.keyboard.copy':'快捷键打开，Enter 保存，Esc 关闭。没有多余步骤。','feature.menu.title':'就在工作流中','feature.menu.copy':'用工具栏图标或网页右键菜单，随时修改需要修改的标签。','feature.local.title':'默认保护隐私','feature.local.copy':'不发起网络请求，不采集遥测，不上传数据。规则和设置都保存在当前设备的 Chrome 存储中。','feature.rules.title':'可见、可控的规则','feature.rules.copy':'在同一处搜索、编辑、暂停、导出和导入每一条永久命名规则。','features.caption':'每条保存的规则都清晰可见、可编辑，并且只存在本地。',
    'advanced.eyebrow':'适合重复性工作','advanced.title':'真正理解<br>你 <em>所在位置</em> 的规则。','advanced.copy':'匹配一个精确 URL、整个域名，或用占位符和正则匹配动态路径。为重复工作建立自己的视觉语言。','advanced.link':'探索高级规则','advanced.example':'捕获真正重要的部分，让它出现在标签标题里。',
    'faq.title':'几个常见问题。','faq.one.q':'Tab Rename 会收集我的数据吗？','faq.one.a':'不会。页面标题、网址、规则和设置都只在浏览器中处理和保存。Tab Rename 不发起网络请求，也不使用遥测。','faq.two.q':'哪些页面可以重命名？','faq.two.a':'绝大多数普通网页都可以。chrome://、Chrome 应用商店、新标签页及其他扩展页面等受 Chrome 保护的页面无法修改。','faq.three.q':'多个规则重叠时如何处理？','faq.three.a':'优先级依次为：精确 URL、URL 模式、域名。直接在页面或标签会话中设置的名称始终优先于保存的规则。','faq.four.q':'为什么会请求可选网站权限？','faq.four.a':'可选网站权限让永久规则在页面跳转后自动应用。你可随时拒绝或在 Chrome 中撤销；手动重命名依然可用。',
    'final.eyebrow':'腾出空间，好好思考','final.title':'你的标签已经说得够多了。<br><em>让它说对的话。</em>','final.cta':'将 Tab Rename 添加至 Chrome','footer.note':'更安静的浏览方式。','footer.privacy':'隐私协议','back':'← 返回首页',
    'advancedpage.eyebrow':'高级规则','advancedpage.title':'让重复工作<br>自己 <em>命名。</em>','advancedpage.copy':'一条规则可以精确到一个 URL，也可以覆盖整个域名。所有内容都保存在本地、清晰可见，并由你掌控。','type.exact.title':'精确 URL','type.exact.copy':'为一个固定页面起一个可靠的名字。适合仪表盘、文档或你全天频繁访问的链接。','type.pattern.title':'URL 模式','type.pattern.copy':'使用 {1} 占位符或正则捕获组，处理地址在变化、含义却不变的页面。','type.domain.title':'域名','type.domain.copy':'为同一主机名下的所有页面应用统一清晰的名称。很适合后台与不同环境。','priority.eyebrow':'结果始终可预期','priority.title':'一个页面，一个明确结果。','priority.copy':'多个规则同时匹配时，Tab Rename 会按固定顺序解析。直接在页面中创建的名称总是优先。','priority.one':'页面或标签会话名称','priority.two':'精确 URL','priority.three':'URL 模式','priority.four':'域名','advancedpage.screeneyebrow':'把所有规则放在一起','advancedpage.screentitle':'随时可以调整。','advancedpage.final':'一个更好的标题，<br><em>只需一个快捷键。</em>',
    'privacy.eyebrow':'用人话写的隐私协议','privacy.title':'没有任何内容<br>离开 <em>你的浏览器。</em>','privacy.lead':'Tab Rename 的目的只是整理标签，而不是观察使用它的人。','privacy.one.title':'我们收集什么','privacy.one.copy':'什么也不收集。Tab Rename 不收集、传输、出售或共享个人信息；不发起网络请求，没有分析工具，也没有广告 SDK。','privacy.two.title':'哪些内容留在你的设备上','privacy.two.copy':'永久规则和暂停网站保存在 Chrome 本地存储中；标签会话名称保存在 Chrome 会话存储中；仅当前页面的名称只存在于当前页面的扩展内存中。','privacy.three.title':'为什么需要可选网站权限','privacy.three.copy':'若你选择开启，可选权限会让永久规则在页面导航后继续自动应用。它仅会在你授权的网站上读取和更新当前标签标题。你可随时在 Chrome 中移除该权限。','privacy.four.title':'你拥有的控制权','privacy.four.copy':'你可以在扩展管理页面编辑、禁用、导出或删除规则。卸载扩展会移除其本地浏览器数据。','privacy.contact':'完整源码和问题追踪，请访问 GitHub 项目。'
  }
};

const stored = localStorage.getItem('tab-rename-language');
let language = stored || 'en';
function render(lang) {
  language = lang;
  const dictionary = copy[lang];
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
  document.querySelectorAll('[data-i18n]').forEach((element) => { const value = dictionary[element.dataset.i18n]; if (value) element.textContent = value; });
  document.querySelectorAll('[data-i18n-html]').forEach((element) => { const value = dictionary[element.dataset.i18nHtml]; if (value) element.innerHTML = value; });
  document.querySelectorAll('[data-i18n-aria]').forEach((element) => { const value = dictionary[element.dataset.i18nAria]; if (value) element.setAttribute('aria-label', value); });
  document.querySelectorAll('[data-alt-en]').forEach((element) => { element.alt = lang === 'zh' ? element.dataset.altZh : element.dataset.altEn; });
  document.querySelectorAll('[data-src-en]').forEach((element) => { element.src = lang === 'zh' ? element.dataset.srcZh : element.dataset.srcEn; });
  localStorage.setItem('tab-rename-language', lang);
}
document.querySelector('.language-switch')?.addEventListener('click', () => render(language === 'zh' ? 'en' : 'zh'));
render(language);
